#!/usr/bin/env bash
case "$1" in
    "") stack --install-ghc runghc --package shake exec ./_shake/buildshake
        ;;
    *) stack --install-ghc runghc  --package shake exec ./_shake/buildshake -- "$@"
esac
